### ISSUE TITLE
Uncaught TypeError when listing NoteAttachmentMasterCardAction

### ISSUE THREAD

**Issue by basst85** [bunq/sdk_php#164]
## Steps to reproduce:
I'm using this code:
```PHP
$mastercardActions = MasterCardAction::listing($monetaryAccountId)->getValue();
$mastercardActionId = $mastercardActions[0]->getId();
$mastercardActionAttachments = NoteAttachmentMasterCardAction::listing($mastercardActionId,$monetaryAccountId)->getValue();
```
But it's returning this error:
```
Fatal error: Uncaught TypeError: Argument 1 passed to bunq\Model\Core\BunqModel::createFromResponseArray() must be of the type array, integer given, called in /var/www/domain.com/vendor/bunq/sdk_php/src/Model/Core/BunqModel.php on line 242 
and defined in /var/www/domain.com/vendor/bunq/sdk_php/src/Model/Core/BunqModel.php:103 Stack trace: #0 /var/www/domain.com/vendor/bunq/sdk_php/src/Model/Core/BunqModel.php(242): bunq\Model\Core\BunqModel::createFromResponseArray(3647492, NULL) #1 /var/www/domain.com/vendor/bunq/sdk_php/src/Model/Core/BunqModel.php(207): bunq\Model\Core\BunqModel::createListFromResponseArray(Array) #2 /var/www/domain.com/vendor/bunq/sdk_php/src/Model/Core/BunqModel.php(165): bunq\Model\Core\BunqModel::determineFieldContents(Object(ReflectionProperty), Array) #3 /var/www/domain.com/vendor/bunq/sdk_php/src/Model/Core/BunqModel.php(119): bunq\Model\Core\BunqModel::createInstanceFromResponseArray(Array) #4 /var/www/domain.com/ in /var/www/domain.com/vendor/bunq/sdk_php/src/Model/Core/BunqModel.php on line 103
```

## What should happen:
1. Return a JSON object with attachments

## What happens:
1. Retuns an error

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [1.1.0](https://github.com/bunq/sdk_php/releases/tag/1.1.0)
-  Sandbox
-  Production

## Response id
None

**Comment by OGKevin** [comment]
hmm, @kojoru sounds like a view definition error. Same as #76

**Comment by basst85** [comment]
@OGKevin @kojoru There is something "strange" with the returnvalue of $responseArray in the function fromJsonList() (in BunqModel):
https://pastebin.com/ciGZ7k6L 

The attachment array in bottom is strange, it's no object?

The response JSON:
https://pastebin.com/RbfsYRNW

**Comment by OGKevin** [comment]
so @kojoru this can either be an view definition mistake or the actual response is wrong :)

**Comment by basst85** [comment]
> found it :)
> 
> ```
>           "attachment": {
>                 "id": 3647492,
>                 "description": "",
>                 "content_type": "image\/jpeg"
>             }
> ```
> is an object but, this is how it's defined:
> 
> [sdk_php/src/Model/Generated/Endpoint/NoteAttachmentMasterCardAction.php](https://github.com/bunq/sdk_php/blob/f369d3b931ea833e06d40bda85620506a31568a2/src/Model/Generated/Endpoint/NoteAttachmentMasterCardAction.php#L72-L77)
> 
> Lines 72 to 77 in [f369d3b](/bunq/sdk_php/commit/f369d3b931ea833e06d40bda85620506a31568a2)
> 
>      /** 
>       * The attachment attached to the note. 
>       * 
>       * @var AttachmentMonetaryAccountPayment[] 
>       */ 
>      protected $attachment; 
> So please remove the `[]` from the doc and it should be good.

Yes! That works indeed. Thanks!

**Comment by basst85** [comment]
@kojoru Any update on this small bug?

**Comment by two-trick-pony-NL** [comment]
Hi! We're closing this issue as it's tied to an older version of our SDKs, and we've since completely revamped them as part of bunq Update 28.

This is a fresh start—we've tested the new SDKs extensively, and we’ll be putting them to the test again during our upcoming hackathon this Friday, where we’ll fix idiosyncrasies on the spot. (You’re welcome to [join us](https://www.bunq.com/en-nl/hackathon)!)

If this issue (or a new one) shows up with the updated SDKs, feel free to reopen or file a new report—we're happy to jump on it.
