### ISSUE TITLE
tinker/user-overview returns 500 (Fatal error: Uncaught bunq\Exception\PleaseContactBunqException)

### ISSUE THREAD

**Issue by Iar0** [bunq/sdk_php#169]
## Steps to reproduce:
1. `bash <(curl -s https://tinker.bunq.com/php/setup.sh)`
2. `tinker/user-overview.php `

## What should happen:
1. Should return an account, as describer in https://doc.bunq.com/#/android-emulator (Once installed, run tinker/user-overview, this will create an account for you when necessary)

## What happens: 
Returns a fatal error

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

> Micheles-MacBook-Pro:tinker-php michele$  tinker/user-overview.php 
> *** tinkering cool logo ***
> Fatal error: Uncaught bunq\Exception\PleaseContactBunqException: HTTP Response Code: 500
> The response id to help bunq debug: The response header "X-Bunq-Client-Response-Id" or "x-bunq-client-response-id" could not be found.
> Error message: 
> 
> Encountered unhandled exception.
> 
>  in /Users/michele/dev/tmi/tinker-php/vendor/bunq/sdk_php/src/Exception/ExceptionFactory.php:64
> Stack trace:
> #0 /Users/michele/dev/tmi/tinker-php/vendor/bunq/sdk_php/src/Http/Handler/ResponseHandlerError.php(54): bunq\Exception\ExceptionFactory::createExceptionForResponse(Array, 500, 'The response he...')
> #1 /Users/michele/dev/tmi/tinker-php/vendor/bunq/sdk_php/src/Http/Handler/HandlerUtil.php(42): bunq\Http\Handler\ResponseHandlerError->execute(Object(GuzzleHttp\Psr7\Response))
> #2 /Users/michele/dev/tmi/tinker-php/vendor/guzzlehttp/promises/src/FulfilledPromise.php(39): bunq\Http\Handler\HandlerUtil::bunq\Http\Handler\{closure}(Object(GuzzleHttp\Psr7\Response))
> #3 /Users/michele/dev/tmi/tinker-php/vendor/guzzlehttp/p in /Users/michele/dev/tmi/tinker-php/vendor/bunq/sdk_php/src/Exception/ExceptionFactory.php on line 64

## SDK version and environment
- Tested on [0.10.0](https://github.com/bunq/sdk_php/releases/tag/0.10.0)
- [x] Sandbox
- [ ] Production

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id: The response header "X-Bunq-Client-Response-Id" or "x-bunq-client-response-id" could not be found.

## Additional info
I just tried the java tinker and I successfully created an account, so it sounds like a problem for this SDK and not a server error

**Comment by Iar0** [comment]
I closed this since I had the error using thinker: https://github.com/bunq/tinker_php/issues/32
