### ISSUE TITLE
PHP Creating an API context error

### ISSUE THREAD

**Issue by jeraldpunx** [bunq/sdk_php#210]
## Steps to reproduce:
```
<?php
	require __DIR__ . '/vendor/autoload.php';
    use bunq\Context\ApiContext;
	use bunq\Util\BunqEnumApiEnvironmentType;

	$environmentType = BunqEnumApiEnvironmentType::SANDBOX(); // Can also be BunqEnumApiEnvironmentType::PRODUCTION();
	$apiKey = 'asdasdasdasd'; // Replace with your API key
	$deviceDescription = "JeraldPC"; // Replace with your device description
	$permittedIps = ['0.0.0.0']; // List the real expected IPs of this device or leave empty to use the current IP

	$apiContext = ApiContext::create(
	    $environmentType,
	    $apiKey,
	    $deviceDescription,
	    $permittedIps
	);

	BunqContext::loadApiContext($apiContext);
```

## What should happen:
Create API Context

## What happens:
`Fatal error: Uncaught bunq\Exception\BunqException: Generating a new private key failed. See "http://php.net/manual/en/function.openssl-pkey-new.php" for more info. in D:\laragon\www\bunq\vendor\bunq\sdk_php\src\Security\KeyPair.php:66 Stack trace: #0 D:\laragon\www\bunq\vendor\bunq\sdk_php\src\Context\ApiContext.php(187): bunq\Security\KeyPair::generate() #1 D:\laragon\www\bunq\vendor\bunq\sdk_php\src\Context\ApiContext.php(178): bunq\Context\ApiContext->initializeInstallationContext() #2 D:\laragon\www\bunq\vendor\bunq\sdk_php\src\Context\ApiContext.php(119): bunq\Context\ApiContext->initialize('JeraldPC', Array) #3 D:\laragon\www\bunq\index.php(16): bunq\Context\ApiContext::create(Object(bunq\Util\BunqEnumApiEnvironmentType), 'a6785e1ff4f3964...', 'JeraldPC', Array) #4 {main} thrown in D:\laragon\www\bunq\vendor\bunq\sdk_php\src\Security\KeyPair.php on line 66`

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [1.14.1](https://github.com/bunq/sdk_php/releases/tag/1.14.1)
- [check ] Sandbox
- [ ] Production

**Comment by jeraldpunx** [comment]
help, what is my problem here? I already have openSSL enabled in PHP

**Comment by basst85** [comment]
> help, what is my problem here? I already have openSSL enabled in PHP

Hi,

Can you maybe create (and test) a simple PHP-script with only the following contents?

```php 
<?php
$config = array(
    "digest_alg" => "sha512",
    "private_key_bits" => 2048,
    "private_key_type" => OPENSSL_KEYTYPE_RSA,
);
   
$opensslKeyPair = openssl_pkey_new($config);
```

Because it looks like it's failing on this part of the script

**Comment by basst85** [comment]
Check also this installation info of OpenSSL:
https://www.php.net/manual/en/openssl.installation.php

**Comment by jeraldpunx** [comment]
I'm still having hardtime. The libcrypto exist already on my apache and php but still not works.
![image](https://user-images.githubusercontent.com/5249781/106069030-ab9c2080-613c-11eb-9626-4ba0e0e32965.png)

**Comment by basst85** [comment]
> I'm still having hardtime. The libcrypto exist already on my apache and php but still not works.

Is OpenSSL active and enabled in the PHPinfo output?
https://php.tutorials24x7.com/blog/how-to-configure-php-openssl-module-on-windows

And is the Window Environment Variable "OPENSSL_CONF" also set to the location of openssl.conf ?
https://seegatesite.com/the-steps-how-to-install-openssl-on-xampp-windows/

**Comment by two-trick-pony-NL** [comment]
👋 Hey @jeraldpunx 

I work at bunq and am currently reviewing the bunq API docs, open issues and SDK’s and came across your issue. I know it’s been open for a while, and I’d love to understand how it’s impacting you. Beyond the obvious -fixing this issue-, what else could we do to improve your experience with our API?

If you want to share your thoughts on how we can improve on our public API:

📅 I'd love to schedule a 15 minute interview to understand your needs through: [Calendly](https://calendly.com/pvandoorn-bunq/30min)
💬 Or if you don't have time for a call, you can give us some general feedback through this [form](https://bunqsurvey.typeform.com/to/xMu9sEfw)

Your feedback will go straight to our product team! 🚀

**Comment by two-trick-pony-NL** [comment]
Hi! We're closing this issue as it's tied to an older version of our SDKs, and we've since completely revamped them as part of bunq Update 28.

This is a fresh start—we've tested the new SDKs extensively, and we’ll be putting them to the test again during our upcoming hackathon this Friday, where we’ll fix idiosyncrasies on the spot. (You’re welcome to [join us](https://www.bunq.com/en-nl/hackathon)!)

If this issue (or a new one) shows up with the updated SDKs, feel free to reopen or file a new report—we're happy to jump on it.
