### ISSUE TITLE
Valid IP address rejected

### ISSUE THREAD

**Issue by steffann** [bunq/sdk_php#223]
## Steps to reproduce:
1. Run:
```php
$environmentType = BunqEnumApiEnvironmentType::PRODUCTION();
$apiKey = 'xxx';
$deviceDescription = 'yyy';
$permittedIps = ['185.54.92.3', '2a00:8642:1000:1::3'];

$apiContext = ApiContext::create(
    $environmentType,
    $apiKey,
    $deviceDescription,
    $permittedIps
);
```

## What should happen:
1. This should succeed, as the addresses are the correct addresses for this device

## What happens:
1. We get this error message:
```php

PHP Fatal error:  Uncaught bunq\Exception\BunqException: Invalid ip address "2a00:8642:1000:1::3" in /var/www/xxx/bunq/vendor/bunq/sdk_php/src/Util/InstallationUtil.php:216
```

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

> Stack trace:
> #0 /var/www/xxx/bunq/vendor/bunq/sdk_php/src/Util/InstallationUtil.php(228): bunq\Util\InstallationUtil::assertIpIsValid()
> #1 /var/www/xxx/bunq/vendor/bunq/sdk_php/src/Context/ApiContext.php(113): bunq\Util\InstallationUtil::assertAllIpIsValid()
> #2 /var/www/xxx/bunq/context.php(15): bunq\Context\ApiContext::create()
> #3 {main}
>   thrown in /var/www/xxx/bunq/vendor/bunq/sdk_php/src/Util/InstallationUtil.php on line 216

## SDK version and environment
- Tested on [1.19.9.6](https://github.com/bunq/sdk_php/releases/tag/1.19.9.6)
- [ ] Sandbox
- [X] Production

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id:

## Extra info:
[//]: # (Please provide any other relevant information here)

**Comment by two-trick-pony-NL** [comment]
👋 Hey @steffann 

I work at bunq and am currently reviewing the bunq API docs, open issues and SDK’s and came across your issue. I know it’s been open for a while, and I’d love to understand how it’s impacting you. Beyond the obvious -fixing this issue-, what else could we do to improve your experience with our API?

If you want to share your thoughts on how we can improve on our public API:

📅 I'd love to schedule a 15 minute interview to understand your needs through: [Calendly](https://calendly.com/pvandoorn-bunq/30min)
💬 Or if you don't have time for a call, you can give us some general feedback through this [form](https://bunqsurvey.typeform.com/to/xMu9sEfw)

Your feedback will go straight to our product team! 🚀

**Comment by two-trick-pony-NL** [comment]
Hi! We're closing this issue as it's tied to an older version of our SDKs, and we've since completely revamped them as part of bunq Update 28.

This is a fresh start—we've tested the new SDKs extensively, and we’ll be putting them to the test again during our upcoming hackathon this Friday, where we’ll fix idiosyncrasies on the spot. (You’re welcome to [join us](https://www.bunq.com/en-nl/hackathon)!)

If this issue (or a new one) shows up with the updated SDKs, feel free to reopen or file a new report—we're happy to jump on it.
